### ISSUE TITLE
Cannot easily create "false"^^xsd:boolean literal

### ISSUE THREAD

**Issue by tpluscode** [zazuko/clownface#22]
Calling `cf.literal(false)` does not return a new clownface instance

**Comment by tpluscode** [comment]
@bergos by the way I noticed that `rdf-data-model` has the same problem

**Comment by bergos** [comment]
You should use only values of type `string` according to the [spec](http://rdf.js.org/data-model-spec/#datafactory-interface). There is no type check, cause I want to keep it open. E.g. for the `POST` requests with relative IRIs it's very usefull that there is no check if the IRI is valid. We discussed if valid IRIs should be enforced when we wrote the spec. I hope the missing type check doesn't cause to much trouble/confusion. Anyway, most people should use clownface or some other library on that level.
