### ISSUE TITLE
Add method(s) to filter the results based on termType

### ISSUE THREAD

**Issue by bergos** [zazuko/clownface#25]
There should be one or multiple methods to filter the results based on the `termType`. This can be done already with the `.filter` method, but there should be a shorter, more readable option to handle such cases. The filter code for a `NamedNode` would look like this:

```javascript
cf.filter(cf => termType === 'NamedNode')
```

**Comment by tpluscode** [comment]
This can be done using [is-graph-pointer](https://www.npmjs.com/package/is-graph-pointer)
