### ISSUE TITLE
Return this on forEach()

### ISSUE THREAD

**Issue by l00mi** [zazuko/clownface#30]
For each should return the clownface object instance from which it was invoked.

https://github.com/rdf-ext/clownface/blob/master/lib/Clownface.js#L95

**Comment by tpluscode** [comment]
Could you be more specific?

**Comment by l00mi** [comment]
The idea is to be able to chain the result given to `forEach()` to other CF methods.

E.g. `cf.out(rdfs.type).forEach(x => {console.log(x)}).out(rdfs.label).forEach(z = {console.log(z.value)})`.
