### ISSUE TITLE
Without context, addOut creates blank subjects

### ISSUE THREAD

**Issue by tpluscode** [zazuko/clownface#33]
Same would likely apply to `addIn` and the created objects

```js
const cf = require("clownface")
const { dataset } = require('rdf-ext')
const { rdf, schema } = require('@tpluscode/rdf-ns-builders')

const graph = cf({ dataset: dataset() })

graph.addOut(rdf.type, schema.Person)

;[...graph.dataset][0].subject
```

## Current

The code above creates an `undefined` subject in that quad

## Expected

Initially I thought that maybe this should be a silent no-op but then maybe it would just generate hard to track errors down the line for consumers.

Should it just throw?

**Comment by bergos** [comment]
No error should be thrown. Think of the following you case: You select multiple terms with `.has` and now you want to attach a new quad for every selected quad:

```javascript
ptr
  .has(ns.rdf.type, ns.ex.Resource)
  .addOut(ns.ex.lastChange, rdf.literal((new Date()).toISOString()))
```

If you care about having at least one `ns.ex.Resource`, a more explicit check in the code should be done before calling `.addOut()`.

Maybe it could be a little bit more clear in the documentation that a quad is added for each `term` in the current context. That means 0-n quads are created.

**Comment by tpluscode** [comment]
`ptr.has()` does actually create underlying pointers os it a safe operation

In the example I show there is no node being pointed, not context and this causes `undefined` terms in quads

**Comment by bergos** [comment]
Yes, right, it's a little bit different. Still I would just ignore a context without a term. I think we don't have any methods yet where context objects with term and without could be mixed in one clownface object, but for the future I guess it would be more consistent to handle it without errors.

**Comment by tpluscode** [comment]
> I guess it would be more consistent to handle it without errors.

So you mean that no quad should be added?
