### ISSUE TITLE
better handling of non-list or empty list object values in .list()

### ISSUE THREAD

**Issue by bergos** [zazuko/clownface#37]
With the current code the following example creates an array with `undefined` as the only element. 

```javascript
const rdf = require('rdf-ext')
const clownface = require('.')

const subject = rdf.namedNode('http://example.org/subject')
const predicate = rdf.namedNode('http://example.org/predicate')
const ptr = clownface({ dataset: rdf.dataset(), term: subject })
const list = ptr.list(predicate)
console.log([...list].map(e => e.term))
```

The return value should be `null` for this case.

Here a full list of edge cases and the expected return values:

### empty list

```turtle
<subject> <predicate> ().
```

```javascript
[]
```

### non list object

```turtle
<subject> <predicate> "test".
```

```javascript
null
```

### no matching triple

```turtle
# no triple
```

```javascript
null
```

The documentation should be extended to show how a non-list object can be combined with `.out`:

```javascript
const list = shape.list(ns.sh.path)
const values = (list && [...list]) || [shape.out(ns.sh.path)]
```

**Comment by tpluscode** [comment]
`list()` does not take parameter, mind you. The non-list lay be a legitimate case. Are you sure you want to return null though?

From another perspective. What is a non-list?

1. literal, surely
2. node without `rdf:first`
3. node without `rdf:rest`

Maybe it is more sensible to also return and empty array?

**Comment by bergos** [comment]
The N-Triples for an empty list should look like this:

```turtle
<subject> <predicate> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>.
```

That should allow us to identify an empty list by `term.equals(rdf:nil)`. If there is a `rdf:first`, it's a list with elements. Everything else is a non-list. I think with that logic we can distinguish and we should. E.g. there is a difference between having an empty whitelist or not having one at all.
