### ISSUE TITLE
Feature request: Provide some immutable update methods

### ISSUE THREAD

**Issue by allforabit** [zazuko/clownface#49]
Thanks for the great lib! I'm using it with react and it works fairly seamlessly after some figuring out. One nice to have would be some immutable update methods similar to the query methods. I.e. instead of adding to a dataset or removing it would return a new instance of clownface with a cloned version of the dataset with the changes made to it. This would be used in `setState` and `useReducer` then and it would make it less likely to silently update the dataset. At the moment I'm just running the updates and then calling setState to trigger and update along with some memoization to minimize component updates.

**Comment by bergos** [comment]
Maybe wrapping the dataset with [rdf-dataset-changelog](https://www.npmjs.com/package/rdf-dataset-changelog) could solve your problem?

**Comment by allforabit** [comment]
Wow looks really cool, thanks v much will give that a spin!
