### ISSUE TITLE
.out with language not returning expected literals

### ISSUE THREAD

**Issue by tpluscode** [zazuko/clownface#53]
Consider a resource with only tagged labels, with primary tgs

```turtle
<> rdfs:label "foo"@en , "le foo"@fr , "das Foo"@de .
```

What should be the output of `.out(rdfs.label, { language: [ 'en-US' ] })` ?

Right now it returns nothing but I think that a more specific language should implicitly be followed by less specific ones. So for example a filtered out by a tertiary tag 

```js
ptr.out(rdfs.label, { language: [ 'de-DE-1990', 'en' ] })
```

should be equivalent to

```js
ptr.out(rdfs.label, { language: [ 'de-DE-1990', 'de-DE', 'de', 'en' ] })
```

**Comment by bergos** [comment]
I don't think clownface should implement that feature. With that feature it would be no longer possible to explicitly ask for a more specific language.

If there is an issue with some browsers, a util function could generate an optimized language array. Using `navigator.languages` as default value should even shorten the code:

```javascript
function optimizedLanguages(languages = navigator.languages) {
  // ...
}

ptr.out(rdfs.label, { language: optimizedLanguages() })
```

But such a util function should not be part of clownface.
