### ISSUE TITLE
list() does not always return an iterator

### ISSUE THREAD

**Issue by LaurensRietveld** [zazuko/clownface#61]
The [function description](https://github.com/zazuko/clownface/blob/479607facdc687b4b5a006bba8faa80445e9e9c2/lib/Clownface.js#L136) of `list()` says that it always returns an iterator. In reality, it does not:

```js
 if (this.term) {
      if (this.term.termType !== 'NamedNode' && this.term.termType !== 'BlankNode') {
        return null
      }

      if (!this.term.equals(this.namespace.nil) && !this.out(this.namespace.first).term) {
        return null
      }
    }
```

This causes issues in e.g. the shacl validator where a spread operator is applied to the `list()` result (see [here](https://github.com/zazuko/rdf-validate-shacl/blob/3e1d6c931d7cb3f4be8dcb665cd3aa67dacab069/src/dataset-utils.js#L91))

Depending on the structure of your data, this leads to obscure errors such as `listNode.list is not a function or its return value is not iterable`

**Comment by l00mi** [comment]
Thank you for pointing this out.

https://github.com/zazuko/clownface/blob/479607facdc687b4b5a006bba8faa80445e9e9c2/lib/Clownface.js#L138 states that it can return `null`.  Do you refer to something else?

@bergos do you remember why we went for `null` over an empty list?

@martinmaillard can https://github.com/zazuko/rdf-validate-shacl deal with this?

**Comment by LaurensRietveld** [comment]
Ah, I mistakenly added links to files instead of lines. I wanted to refer to [this line](https://github.com/zazuko/clownface/blob/479607facdc687b4b5a006bba8faa80445e9e9c2/lib/Clownface.js#L136). You're right in that the `@returns` tag is correct here. 

Let me know if the validate-shacl library is a better place for ticket and I'll make an issue there

**Comment by tpluscode** [comment]
This is by design, IIRC to distinguish between an empty list `( )` and a non-list

**Comment by LaurensRietveld** [comment]
thanks! I'll report this in the validate-shacl repo then

**Comment by LaurensRietveld** [comment]
see https://github.com/zazuko/rdf-validate-shacl/issues/73
