### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by vid** [zazuko/clownface#64]
If people search for "clownface," they're going to get "A deranged serial killer known as "Clownface" terrorises the residents of a small town. killer clownmaskmasked killerb horrorslasher."

How about this for a name: graphlim

**Comment by l00mi** [comment]
Let's change that and become the hit number one on google with our _clownface_, if you search **clownface rdf**, we are already there. The origin of the name is https://en.wikipedia.org/wiki/Eskimo_Nebula btw.

But thank you for your concern, for now we like to stick for the term. I am curious, would the name practically stop or inhibit to use the library in any context?

**Comment by vid** [comment]
It would cause second thought, which can be fatal. Why not avoid it?
Names that are meaningful, unique yet whimsical are great. graphlim = graph + liminal. It would always be found, without any trouble. (I spent a week on Wikipedia trying to get the name "Christine" to at least redirect to a disambiguation page, rather than the horror film. A problem with who controls names).
Since you asked, personally, I resent the way hollywood claims popular associations for its own franchises. "Clownface" is an example of that. Though, I don't like clowns either. But it all adds up to someone like myself not using the library without second or third thoughts. And I have a lot of things to do that involve decisions.
If you want more reasons, the use of "clownface" [isn't accepted](https://en.wikipedia.org/wiki/Eskimo_Nebula#Naming_controversy) for the nebula.
